app = "nama-aplikasi-anda"
primary_region = "sin" # Ubah ke region yang sesuai, misalnya "sin" untuk Singapura

[build]
  builder = "paketobuildpacks/builder:base"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
